{
 "title": "KafkaJS",
 "description": "Sample Dashboard for KafkaJS Prometheus Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "producer_client_id",
    "label": "Producer Client Id",
    "query": {
     "query": "label_values(kafka_producer_connection_count,client_id)"
    }
   },
   {
    "name": "consumer_client_id",
    "label": "Consumer Client Id",
    "query": {
     "query": "label_values(kafka_consumer_connection_count,client_id)"
    }
   },
   {
    "name": "producer_broker",
    "label": "Producer Broker",
    "query": {
     "query": "label_values(kafka_producer_request_total{client_id=~'$producer_client_id'},broker)"
    }
   },
   {
    "name": "consumer_broker",
    "label": "Consumer Broker",
    "query": {
     "query": "label_values(kafka_consumer_request_total{client_id=~'$consumer_client_id'},broker)"
    }
   },
   {
    "name": "consumer_topic",
    "label": "Consumer Topic",
    "query": {
     "query": "label_values(kafka_consumer_batch_latency_sum{client_id=~'$consumer_client_id'},topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "description": "Number of active connections",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_consumer_connection_count{client_id=~\"$consumer_client_id\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Created Connections Rate",
   "type": "timeseries",
   "description": "The total number of connections established with a broker.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_connection_creation_total{client_id=~\"$consumer_client_id\"}[$__rate_interval])) by (client_id)",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Closed Connections Rate",
   "type": "timeseries",
   "description": "The total number of connections closed with a broker.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_connection_close_total{client_id=~\"$consumer_client_id\"}[$__rate_interval])) by (client_id)",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "The total number of requests sent.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_request_total{client_id=~\"$consumer_client_id\", broker=~\"$consumer_broker\"}[$__rate_interval])) by (client_id, broker)",
     "legendFormat": "{{client_id}} - {{broker}}"
    }
   ]
  },
  {
   "title": "Average Request Size Per Request",
   "type": "timeseries",
   "description": "Average request size per request in bytes.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_request_total{client_id=~\"$consumer_client_id\", broker=~\"$consumer_broker\"}[$__rate_interval])) by (client_id, broker)",
     "legendFormat": "{{client_id}} - {{broker}}"
    }
   ]
  },
  {
   "title": "Request Queue",
   "type": "timeseries",
   "description": "The size of the request queue.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_request_queue_size{client_id=~\"$consumer_client_id\", broker=~\"$consumer_broker\"}) by (client_id, broker)",
     "legendFormat": "{{client_id}} - {{broker}}"
    }
   ]
  },
  {
   "title": "Average Fetch Latency",
   "type": "timeseries",
   "description": "Average Fetch Latency.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_latency_sum{client_id=~\"$consumer_client_id\"}) by (client_id) / sum(kafka_consumer_fetch_latency_count{client_id=~\"$consumer_client_id\"}) by (client_id) ",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Average Batch Latency By Topic",
   "type": "timeseries",
   "description": "Average Batch Latency.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_batch_latency_sum{client_id=~\"$consumer_client_id\", topic=~\"$consumer_topic\"}) by (client_id, topic) / sum(kafka_consumer_batch_latency_count{client_id=~\"$consumer_client_id\", topic=~\"$consumer_topic\"}) by (client_id, topic) ",
     "legendFormat": "{{client_id}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Average Batch Size Per Batch",
   "type": "timeseries",
   "description": "Average batch size by topic in bytes.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_batch_size_total{client_id=~\"$consumer_client_id\", topic=~\"$consumer_topic\"}) by (client_id, topic) / sum(kafka_consumer_batch_latency_count{client_id=~\"$consumer_client_id\", topic=~\"$consumer_topic\"}) by (client_id, topic) ",
     "legendFormat": "{{client_id}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Heartbeat Rate",
   "type": "timeseries",
   "description": "The number of heartbeats with a broker",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_heartbeat_total{client_id=~\"$consumer_client_id\"}[$__rate_interval])) by (client_id, group_id)",
     "legendFormat": "{{client_id}} - {{group_id}}"
    }
   ]
  },
  {
   "title": "Producer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Connections",
     "type": "timeseries",
     "description": "Number of active connections",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_producer_connection_count{client_id=~\"$producer_client_id\"}",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Created Connections Rate",
     "type": "timeseries",
     "description": "The total number of connections established with a broker.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_producer_connection_creation_total{client_id=~\"$producer_client_id\"}[$__rate_interval])) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Closed Connections Rate",
     "type": "timeseries",
     "description": "The total number of connections closed with a broker.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_producer_connection_close_total{client_id=~\"$producer_client_id\"}[$__rate_interval])) by (client_id)",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "timeseries",
     "description": "The total number of requests sent.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_producer_request_total{client_id=~\"$producer_client_id\", broker=~\"$producer_broker\"}[$__rate_interval])) by (client_id, broker)",
       "legendFormat": "{{client_id}} - {{broker}}"
      }
     ]
    },
    {
     "title": "Average Request Size Per Request",
     "type": "timeseries",
     "description": "Average request size per request in bytes.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kafka_producer_request_size_total{client_id=~\"$producer_client_id\", broker=~\"$producer_broker\"}) by (client_id, broker)/ sum(kafka_producer_request_total{client_id=~\"$producer_client_id\", broker=~\"$producer_broker\"}) by (client_id, broker)",
       "legendFormat": "{{client_id}} - {{broker}}"
      }
     ]
    },
    {
     "title": "Request Queue",
     "type": "timeseries",
     "description": "The size of the request queue.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kafka_producer_request_queue_size{client_id=~\"$producer_client_id\", broker=~\"$producer_broker\"}) by (client_id, broker)",
       "legendFormat": "{{client_id}} - {{broker}}"
      }
     ]
    }
   ]
  }
 ]
}