name: Snyk

on:
  push:
    branches: ["main" ]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  pre_snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Get all files that have changed
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: |
            src/**/*.ts
            test/**/*.ts
            package.json
            package-lock.json
  snyk:
    needs: pre_snyk
    if: ${{ needs.pre_snyk.outputs.any_changed == 'true' }}
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Output [${{needs.pre_snyk.outputs.any_changed}}]"
      - uses: actions/checkout@v4
      - name: Get all files that have changed
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            code:
              - 'src/**/*.ts'
              - 'test/**/*.ts'
            package:
              - package.json
              - package-lock.json
      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@master
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      # - name: Snyk monitor 
      #   run: snyk monitor --file=package.json --org=christiangalsterer --project-name='christiangalsterer/kafkajs-prometheus-exporter:package.json' --project-environment=backend --project-lifecycle=production 
      #   env:
      #      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk to check for vulnerabilities
        if: ${{ steps.changed-files.outputs.package_any_changed == 'true' }}
        uses: snyk/actions/node@master
        continue-on-error: true # to make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=christiangalsterer --sarif-file-output=snyk.sarif 
      - name: Upload test result to GitHub Code Scanning
        if: ${{ steps.changed-files.outputs.package_any_changed == 'true' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif    
      - name: Snyk Code Test
        if: ${{ ! (github.event_name == 'pull_request' && github.event.pull_request.user.login == 'renovate[bot]' && contains(github.event.pull_request.labels.*.name, 'renovate')) && (steps.changed-files.outputs.code_any_changed == 'true') }}
        run: snyk code test --org=christiangalsterer --sarif-file-output=snyk_code_test.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload code test result to GitHub Code Scanning
        if: ${{ ! (github.event_name == 'pull_request' && github.event.pull_request.user.login == 'renovate[bot]' && contains(github.event.pull_request.labels.*.name, 'renovate')) && (steps.changed-files.outputs.code_any_changed == 'true') }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk_code_test.sarif
          category: snyk_code_test