name: Snyk

on:
  push:
    branches: ["main" ]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@master
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm i
      # - name: Snyk monitor 
      #   run: snyk monitor --file=package.json --org=christiangalsterer --project-name=package.json --project-environment=backend --project-lifecycle=production 
      #   env:
      #      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=christiangalsterer --sarif-file-output=snyk.sarif 
      - name: Upload test result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif    
      - name: Snyk Code Test
        if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && ! github.event.label.name == 'renovate') }}
        run: snyk code test --org=christiangalsterer --sarif-file-output=snyk_code_test.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload code test result to GitHub Code Scanning
        if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && ! github.event.label.name == 'renovate') }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk_code_test.sarif
          category: snyk_code_test          